"""make public_key and last_login nullable

Revision ID: 52f13f7f3783
Revises: 5083dba02393
Create Date: 2026-03-20 19:48:42.395358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52f13f7f3783'
down_revision: Union[str, Sequence[str], None] = '5083dba02393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'public_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'public_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
