"""fix all nullable fields

Revision ID: d837553be788
Revises: 3d2e048247c8
Create Date: 2026-04-06 11:57:27.306460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd837553be788'
down_revision: Union[str, Sequence[str], None] = '3d2e048247c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('revoked_tokens', 'token_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('users', 'public_key',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'fcm_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('users', 'fcm_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'public_key',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('revoked_tokens', 'token_id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
