"""add fingerprint table

Revision ID: e4267ba8e788
Revises: c1d2e3f4a5b6
Create Date: 2026-06-09 20:02:38.449094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4267ba8e788'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fingerprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_uuid', sa.UUID(), nullable=False),
    sa.Column('finger_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_uuid'], ['devices.device_uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_uuid', 'finger_id', name='uq_device_finger')
    )
    op.drop_index(op.f('ix_user_notifications_user_uuid'), table_name='user_notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_notifications_user_uuid'), 'user_notifications', ['user_uuid'], unique=False)
    op.drop_table('fingerprints')
    # ### end Alembic commands ###
